name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - run: ls -la
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint && pnpm run build

  deploy-storybook:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build-storybook
      - name: Check if gh-pages exists
        id: check_branch
        run: |
          if git ls-remote --heads origin gh-pages; then
            echo "::set-output name=exists::yes"
          else
            echo "::set-output name=exists::no"
          fi
      - name: Create gh-pages if not exists
        if: steps.check_branch.outputs.exists == 'no'
        run: |
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initializing gh-pages branch"
          git push origin gh-pages
          git checkout main
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages  # The branch the action should deploy to.
          folder: .out      # The folder the action should deploy.
